Repository lcobucci/di-builder, pull requests merged in 2022-02, with the labels that each got.

#460 Add known unused package
  .gitattributes
  composer-unused.php
  composer.json
  composer.lock
  src/Generator.php
  test/ContainerBuilderTest.php
Labels: Dependencies

#361 Enforce platform compatibility for PHP 8.1
  .github/workflows/phpunit.yml
Labels: Improvement

#463 Expose and fix incorrect assertion
  Makefile
  src/Generator.php
Labels: Bug
